// User Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_DETAILS_FAIL ='USER_DETAILS_FAIL';
export const USER_DETAILS_SUCCESS ='USER_DETAILS_SUCCESS';
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_LOGOUT = 'USER_LOGOUT';

// Reward Constants
export const REWARD_STATUS_REQUEST = 'REWARD_STATUS_REQUEST';
export const REWARD_STATUS_SUCCESS = 'REWARD_STATUS_SUCCESS';
export const REWARD_STATUS_FAIL = 'REWARD_STATUS_FAIL';

export const REWARD_CLAIM_REQUEST = 'REWARD_CLAIM_REQUEST';
export const REWARD_CLAIM_SUCCESS = 'REWARD_CLAIM_SUCCESS';
export const REWARD_CLAIM_FAIL = 'REWARD_CLAIM_FAIL';

// Other Constants
export const API_BASE_URL = 'http://localhost:5000'; // Update this if needed